version: '3.8'
services:
  srsran:
    image: srsran:latest
    container_name: srsran
    privileged: true
    environment:
      NGAP_LOCAL_ADDR: 192.168.70.163
      NGAP_REMOTE_ADDR: 192.168.70.132 # AMF IP ADDR
      GTPU_LOCAL_ADDR: 192.168.70.163
      MCC: 208
      MNC: 95
      TAC: 0x00a000
      GNBID: 0x19B
      OPC: 63bfa50ee6523365ff14c1f45f88737d
      KEY: 0C0A34601D4F07677303652C0462535B
      DNN: default
      IMSI: 208950000000052
    cap_add:
      - NET_ADMIN
    networks:
      public_net:
          ipv4_address: 192.168.70.163
      public_net_access:
          ipv4_address: 192.168.72.163
    healthcheck:
      test: /bin/bash -c "ip addr | grep uetun1"
      interval: 10s
      timeout: 5s
      retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
    public_net_access:
        external:
            name: oai-public-access
